dbtpackv2:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: test-project-id
      dataset: dbtpackv2_dev
      location: US
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
      # For testing without real credentials, we'll use a placeholder
      keyfile: /dbt/credentials/service-account-key.json
      
    prod:
      type: bigquery
      method: service-account
      project: test-project-id
      dataset: dbtpackv2_prod
      location: US
      threads: 4
      timeout_seconds: 300
      priority: batch
      retries: 3
      keyfile: /dbt/credentials/service-account-key.json 